#!/usr/bin/env python3
"""
This module lists all MongoDB databases using pymongo.
"""

from pymongo import MongoClient


def list_databases():
    """
    Connects to MongoDB and prints the names of all databases.
    """
    client = MongoClient()
    db_list = client.list_database_names()
    for db in db_list:
        print(db)


if __name__ == "__main__":
    list_databases()
